version: '3.7'

services:
  api:
    container_name: api
    build: ../api
    command: npm run server:api
    env_file:
      - ../api/.env
    volumes:
      - ../api/:/app/
      - /app/node_modules/
    ports:
      - 3000:3000
  database-postgres:
    image: postgres:12.2
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password