version: "3.7"

services:
  api-test:
    container_name: api-test
    build: ../api
    tty: true
    env_file:
      - ../api/.env.test
    volumes:
      - ../api/:/app/
      - /app/node_modules/
  database-postgres-test:
    image: postgres:12.2
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
